---
apiVersion: v1
kind: Service
metadata:
  name: flood-exporter
  labels:
    app: flood-exporter
spec:
  ports:
  - name: http
    port: 80
    targetPort: 7979
  selector:
    app: flood-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flood-exporter
spec:
  selector:
    matchLabels:
      app: flood-exporter
  endpoints:
    - port: http
      honorLabels: true
