name: flood-exporter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/login-action@v1
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./containers/flood-exporter
          file: ./containers/flood-exporter/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/46bit/flood-exporter:latest
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{secrets.K8S_URL}}
          k8s-secret: ${{secrets.K8S_SECRET}}
        id: setcontext
      - name: deploy-flood-exporter
        run: |
          kubectl apply -f ./k8s/flood-exporter.yml
