name: flood-exporter
on:
  workflow_dispatch: {}
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{secrets.K8S_URL}}
          k8s-secret: ${{secrets.K8S_SECRET}}
        id: setcontext

      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./containers/flood-exporter
          file: ./containers/flood-exporter/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/46bit/flood-exporter:latest
          push: true
      - name: deploy-flood-exporter
        run: |
          ./manifests/flood-exporter/apply.sh  
